syntax_theme = "EightiesDark"

[[verbs]]
key = "ctrl-k"
execution = ":line_up"
[[verbs]]
key = "ctrl-j"
execution = ":line_down"
[[verbs]]
key = "ctrl-l"
execution = ":panel_right"
[[verbs]]
key = "ctrl-h"
execution = ":panel_left"

[[verbs]]
key = "ctrl-b"
execution = ":page_up"
[[verbs]]
key = "ctrl-f"
execution = ":page_down"

[[verbs]]
key = "ctrl-space"
execution = ":toggle_stage"

[[verbs]]
invocation = "terminal"
key = "enter"
external = "nvrmux send {file}"
apply_to = "file"
leave_broot = false

[[verbs]]
invocation = "up"
key = "ctrl-["
execution = ":focus {root}/.."

[ext-colors]
png = "rgb(255, 128, 75)"
rs = "yellow"
toml = "ansi(105)"
ts = "rgb(0, 122, 205)"
tsx = "rgb(0, 122, 205)"
