#!/bin/bash

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install -y git wget curl python-dev python-pip python3-dev python3-pip neovim tmux silversearcher-ag

pip install neovim
pip3 install neovim

curl -sSf https://static.rust-lang.org/rustup.sh | sh
