#!/bin/bash

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install -y git wget curl python-dev python-pip python3-dev python3-pip neovim tmux silversearcher-ag

pip install neovim
pip3 install neovim

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
nvm install 4
nvm use 4

npm install -g eslint babel-eslint eslint-plugin-react

curl -sSf https://static.rust-lang.org/rustup.sh | sh
