#!/bin/bash

BASE=$(pwd)
export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.config/nvim/autoload
curl --insecure -fLo ~/.config/nvim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim
ln -sf $BASE/init.vim ~/.config/nvim/init.vim
ln -sf $BASE/snippets ~/.config/nvim/UltiSnips

nvim +PlugInstall +qall
