#!/bin/sh

export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

if [ -n $TMUX ]; then
  export NVIM_TUI_ENABLE_TRUE_COLOR=1
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias gitv='git log --graph --format="%C(auto)%h%d %s %C(black)%C(bold)%an, %cr"'
alias gitme='git log --author="$(git config user.name)"'
alias opentorrent='peerflix --vlc -n -d --list '
alias k="kubectl"
alias groot="git rev-parse --show-toplevel"
cdup() {
  fdup --relative-to $(git rev-parse --show-toplevel)
}
alias ghmerge="gh pr comment -b \"/merge\""
alias ghstaging="gh pr comment -b \"/to-staging\""
alias ghcreate="gh pr create --web"
alias ghview="gh pr view --web"
ghintegrate() {
  gh pr comment -b "/integrate -dfs $1"
}

export EDITOR=nvim
#
# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

export TERM=xterm-256color

if [ -d "$HOME/dotfiles/bin" ]; then
  export PATH=$PATH:$HOME/dotfiles/bin
fi

alias reload="exec $SHELL -l"
